// ─── Enemy data + wave config ─────────────────────────────────────────────────
// Placeholder icons digunakan sebagai visual sementara.

export const ENEMY_TEMPLATES = {
  goblin: {
    id: "goblin",
    name: "Goblin",
    category: "Enemy — Pest",
    icon: "🐗",
    hp: 55,
    attackInterval: 6000,
    dmg: 8,
    boardEffect: "Every 10s: locks 1 random block for 4s.",
    defeatCondition: "Any ×2+ combo clears it.",
    onDefeat: "Drops Heal Shard (30% chance).",
    special: "Pack Cackle: If 2+ Goblins active, interval reduces to 4s.",
  },
  goblinBoss: {
    id: "goblinBoss",
    name: "Goblin Boss",
    category: "Enemy — Mini Boss",
    icon: "👹",
    hp: 130,
    attackInterval: 8000,
    dmg: 16,
    boardEffect: "Every 15s: spawns 2 Goblin obstacles on random board cells.",
    defeatCondition: "Requires ×3+ combo OR 3 separate ×2 combos.",
    onDefeat: "Drops Ward + Combo Surge.",
    special: "Berserker: Below 50% HP, interval drops to 5s and damage rises to 22.",
  },
  undead: {
    id: "undead",
    name: "Undead",
    category: "Enemy — Undead",
    icon: "🧟",
    hp: 70,
    attackInterval: 7000,
    dmg: 10,
    boardEffect: "Every 12s: poisons 2 random blocks (matching them deals −3 HP to player).",
    defeatCondition: "Light-type block combo OR any ×3+ combo.",
    onDefeat: "Clears all poison blocks on board.",
    special: "Undying: Revives once at 20 HP unless defeated by a ×3+ combo.",
  },
  mutatedUndead: {
    id: "mutatedUndead",
    name: "Mutated Undead",
    category: "Enemy — Undead",
    icon: "🧌",
    hp: 110,
    attackInterval: 8000,
    dmg: 13,
    boardEffect: "Every 14s: contaminates 1 full column — blocks in it lose 1 combo value.",
    defeatCondition: "Fire-type block combo OR ×3+ combo.",
    onDefeat: "Death Bloom: poisons all blocks in a 3×3 radius.",
    special: "Spore Cloud: contaminated columns persist 5s after it dies unless cleared.",
  },
  duskSkeleton: {
    id: "duskSkeleton",
    name: "Dusk Skeleton",
    category: "Enemy — Undead",
    icon: "💀",
    hp: 85,
    attackInterval: 9000,
    dmg: 11,
    boardEffect: "Every 5th attack: gains a 20 HP shield that blocks all damage until broken.",
    defeatCondition: "Light-type combo breaks shield; ×3+ combo defeats it.",
    onDefeat: "Drops Freeze powerup.",
    special: "Dusk Ascension: At 60s survived, permanently gains +5 dmg per hit.",
  },
  werewolf: {
    id: "werewolf",
    name: "Werewolf",
    category: "Enemy — Beast",
    icon: "🐺",
    hp: 150,
    attackInterval: 10000,
    dmg: 18,
    boardEffect: "Human form (first 30s): shuffles 3 random blocks every 20s. Beast form: shuffles entire board every 15s.",
    defeatCondition: "×3+ combo in human form; ×4 combo required in beast form.",
    onDefeat: "Drops Blood Pact + Combo Surge.",
    special: "Moon Rage: Transforms to beast form after 30s — interval drops to 6s, dmg rises to 28.",
  },
  walyanArcher: {
    id: "walyanArcher",
    name: "Walyan Archer",
    category: "Enemy — Human",
    icon: "🏹",
    hp: 65,
    attackInterval: 5000,
    dmg: 9,
    boardEffect: "Every 8s: destroys 1 block type, targeting the type the player has most of.",
    defeatCondition: "Any ×2+ combo; or matching the targeted block type 3× in a row.",
    onDefeat: "Drops Clarity powerup.",
    special: "Eagle Eye: Once per stage, permanently removes 1 block type for 10s.",
  },
  walyanSoldier: {
    id: "walyanSoldier",
    name: "Walyan Soldier",
    category: "Enemy — Human",
    icon: "🛡️",
    hp: 90,
    attackInterval: 8000,
    dmg: 12,
    boardEffect: "Every 12s: pushes one random column down by 1 row (overflow blocks lost).",
    defeatCondition: "Explosive-type block combo OR ×3+ combo.",
    onDefeat: "Drops Ward powerup.",
    special: "Formation: If another Walyan unit is active, both take 20% less combo damage.",
  },
  walyanPaladin: {
    id: "walyanPaladin",
    name: "Walyan Paladin",
    category: "Enemy — Human",
    icon: "✝️",
    hp: 120,
    attackInterval: 10000,
    dmg: 15,
    boardEffect: "Every 18s: purges all dark/shadow-type blocks from the board entirely.",
    defeatCondition: "Dark-type block combo OR ×4 combo.",
    onDefeat: "Drops Ignite powerup.",
    special: "Divine Shield: Once per fight, nullifies one full player combo (no damage dealt).",
  },
  forestBandit: {
    id: "forestBandit",
    name: "Forest Bandit",
    category: "Enemy — Human",
    icon: "🗡️",
    hp: 60,
    attackInterval: 6000,
    dmg: 7,
    boardEffect: "Every 10s: plants 1 trap block — if matched, deals 8 dmg back to player.",
    defeatCondition: "Any ×2+ combo; trap blocks auto-detonate on ×3+.",
    onDefeat: "Drops Heal Shard.",
    special: "Ambush: If player triggers a trap, Bandit attacks again immediately.",
  },
  stormfjordRaider: {
    id: "stormfjordRaider",
    name: "Stormfjord Raider",
    category: "Enemy — Human",
    icon: "❄️",
    hp: 100,
    attackInterval: 9000,
    dmg: 14,
    boardEffect: "Every 20s: charges a slam — if not interrupted, deals 40 dmg flat.",
    defeatCondition: "×3+ combo interrupts charge; ×2 combo does half damage only.",
    onDefeat: "Drops Combo Surge.",
    special: "Berserker Charge: Charged slam ignores Ward powerup.",
  },
  stormfjordSoldier: {
    id: "stormfjordSoldier",
    name: "Stormfjord Soldier",
    category: "Enemy — Human",
    icon: "🥶",
    hp: 80,
    attackInterval: 7000,
    dmg: 11,
    boardEffect: "Every 12s: freezes 1 full row for 6s (blocks unmatchable).",
    defeatCondition: "Fire-type block combo OR ×3+ combo.",
    onDefeat: "Thaws all frozen rows immediately on defeat.",
    special: "Ice Reflection: Ice-type combos deal 5 splash dmg back to player.",
  },
  stormfjordRefugee: {
    id: "stormfjordRefugee",
    name: "Stormfjord Refugee",
    category: "Enemy — Human",
    icon: "🧥",
    hp: 50,
    attackInterval: 5000,
    dmg: 4,
    boardEffect: "Every 8s: corrupts 1 random block into a grey useless block.",
    defeatCondition: "Any ×2+ combo instantly defeats it.",
    onDefeat: "30% chance to drop Heal Shard.",
    special: "Desperation: At ≤15 HP, corrupts 5 blocks instantly before dying.",
  },
  manfrog: {
    id: "manfrog",
    name: "Manfrog",
    category: "Enemy — Beast",
    icon: "🐸",
    hp: 95,
    attackInterval: 8000,
    dmg: 12,
    boardEffect: "Every 14s: slimes 1 full row — slimed blocks count as −1 combo value.",
    defeatCondition: "Fire-type block combo clears slime + damages; ×3+ defeats.",
    onDefeat: "Clears all slime on board on defeat.",
    special: "Bog Pull: Once per fight, permanently removes 1 block type for 8s.",
  },
  giantSpider: {
    id: "giantSpider",
    name: "Giant Spider",
    category: "Enemy — Beast",
    icon: "🕷️",
    hp: 115,
    attackInterval: 9000,
    dmg: 14,
    boardEffect: "Every 15s: webs 2 random columns together — matching one pulls the other down.",
    defeatCondition: "Fire or Light-type combo clears webs; ×3+ defeats.",
    onDefeat: "Drops Ward powerup; clears all webs on defeat.",
    special: "Egg Sac: On defeat without a ×4 combo, spawns 3 Spider obstacles on board.",
  },
  spider: {
    id: "spider",
    name: "Spider",
    category: "Enemy — Beast",
    icon: "🕸️",
    hp: 40,
    attackInterval: 4000,
    dmg: 5,
    boardEffect: "Every 8s: injects venom into 1 block — matching it deals −2 HP to player.",
    defeatCondition: "Any ×2+ combo; AOE fire/lightning hits all Spiders at once.",
    onDefeat: "10% chance to drop Heal Shard.",
    special: "Web Retreat: 40% chance to dodge a ×3 combo and reposition to a random cell.",
  },
};

export const DEFAULT_WAVE_IDS = [
  "goblin",
  "forestBandit",
  "walyanArcher",
  "stormfjordRefugee",
  "walyanSoldier",
  "undead",
  "goblinBoss",
  "mutatedUndead",
  "manfrog",
  "stormfjordSoldier",
  "duskSkeleton",
  "giantSpider",
  "werewolf",
  "walyanPaladin",
];

const RANDOM_WAVE_TIERS = {
  tier1: ["goblin", "forestBandit", "stormfjordRefugee", "spider"],
  tier2: ["walyanArcher", "walyanSoldier", "stormfjordSoldier", "undead", "manfrog"],
  tier3: [
    "goblinBoss",
    "mutatedUndead",
    "duskSkeleton",
    "stormfjordRaider",
    "walyanPaladin",
    "giantSpider",
    "werewolf",
  ],
};

function randFrom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function createRandomWaves(count = 8) {
  return Array.from({ length: count }, (_, index) => {
    if (index < 2) {
      return randFrom(RANDOM_WAVE_TIERS.tier1);
    }
    if (index < 5) {
      return randFrom([...RANDOM_WAVE_TIERS.tier1, ...RANDOM_WAVE_TIERS.tier2]);
    }
    return randFrom([...RANDOM_WAVE_TIERS.tier2, ...RANDOM_WAVE_TIERS.tier3]);
  });
}
