export const PLAYER_STATS = {
  name: "You",
  description: "The hero on the board, fighting to survive every match.",
  maxHP: 20000,
  damageMin: 10,
  damageMax: 14,
};

export const ENEMIES = {
  Goblin: {
    key: "Goblin",
    name: "Goblin",
    type: "Enemy — Pest",
    description: "A scrawny, cackling pest. Weak alone but irritating in packs.",
    maxHP: 5,
    damageMin: 6,
    damageMax: 8,
    attackInterval: 10000,
    points: 10,
    weakness: "Any ×2+ combo clears it",
    reward: "Drops Heal Shard (30% chance)",
    ability: "Every 10s: locks 1 random block for 4s",
  },
  GoblinBoss: {
    key: "GoblinBoss",
    name: "Goblin Boss",
    type: "Enemy — Mini Boss",
    description: "A bloated chieftain who rules through fear. Summons grunts while the player scrambles.",
    maxHP: 130,
    damageMin: 8,
    damageMax: 16,
    attackInterval: 15000,
    points: 30,
    weakness: "Requires ×3+ combo OR 3 separate ×2 combos",
    reward: "Drops Ward + Combo Surge",
    ability: "Every 15s: spawns 2 Goblin obstacles on random board cells",
  },
  Undead: {
    key: "Undead",
    name: "Undead",
    type: "Enemy — Undead",
    description: "A shambling corpse that won't stay dead — and poisons everything it touches.",
    maxHP: 70,
    damageMin: 7,
    damageMax: 10,
    attackInterval: 12000,
    points: 15,
    weakness: "Any ×3+ combo",
    reward: "Clears all poison blocks on board",
    ability: "Every 12s: poisons 2 random blocks (matching them deals −3 HP to player)",
  },
  MutatedUndead: {
    key: "MutatedUndead",
    name: "Mutated Undead",
    type: "Enemy — Undead",
    description: "A grotesque corpse warped by alchemical experiments. Its death is almost as dangerous as its life.",
    maxHP: 110,
    damageMin: 8,
    damageMax: 13,
    attackInterval: 14000,
    points: 22,
    weakness: "Any ×3+ combo",
    reward: "Death Bloom: poisons all blocks in a 3×3 radius on defeat",
    ability: "Every 14s: contaminates 1 full column — blocks in it lose 1 combo value",
  },
  DuskSkeleton: {
    key: "DuskSkeleton",
    name: "Dusk Skeleton",
    type: "Enemy — Undead",
    description: "An ancient skeleton that grows nearly indestructible every few turns.",
    maxHP: 85,
    damageMin: 9,
    damageMax: 11,
    attackInterval: 20000,
    points: 18,
    weakness: "Any ×3+ combo",
    reward: "Drops Freeze powerup",
    ability: "Every 5th attack: gains a 20 HP shield that blocks all damage until broken",
  },
  Werewolf: {
    key: "Werewolf",
    name: "Werewolf",
    type: "Enemy — Beast",
    description: "A cursed hunter — man by day, savage beast by night.",
    maxHP: 150,
    damageMin: 10,
    damageMax: 18,
    attackInterval: 20000,
    points: 40,
    weakness: "Any ×4 combo",
    reward: "Drops Blood Pact + Combo Surge",
    ability: "Human form first 30s: shuffles 3 random blocks every 20s",
  },
  WalyanArcher: {
    key: "WalyanArcher",
    name: "Walyan Archer",
    type: "Enemy — Human",
    description: "A cold-eyed imperial scout trained to disrupt before the player can react.",
    maxHP: 65,
    damageMin: 5,
    damageMax: 9,
    attackInterval: 8000,
    points: 18,
    weakness: "Any ×2+ combo",
    reward: "Drops Clarity powerup",
    ability: "Every 8s: destroys 1 random block from the board",
  },
  WalyanSoldier: {
    key: "WalyanSoldier",
    name: "Walyan Soldier",
    type: "Enemy — Human",
    description: "A disciplined legionnaire in heavy armour. Pushes and compresses the board.",
    maxHP: 90,
    damageMin: 8,
    damageMax: 12,
    attackInterval: 12000,
    points: 22,
    weakness: "Any ×3+ combo",
    reward: "Drops Ward powerup",
    ability: "Every 12s: pushes one random column down by 1 row (blocks overflow = lost)",
  },
  WalyanPaladin: {
    key: "WalyanPaladin",
    name: "Walyan Paladin",
    type: "Enemy — Human",
    description: "A zealous holy warrior who purges darkness from the board itself.",
    maxHP: 120,
    damageMin: 10,
    damageMax: 15,
    attackInterval: 18000,
    points: 28,
    weakness: "Any ×4 combo",
    reward: "Drops Ignite powerup",
    ability: "Every 18s: purges all dark blocks from the board entirely",
  },
  ForestBandit: {
    key: "ForestBandit",
    name: "Forest Bandit",
    type: "Enemy — Human",
    description: "A desperate outlaw who cheats, traps, and corrupts to survive.",
    maxHP: 60,
    damageMin: 6,
    damageMax: 7,
    attackInterval: 10000,
    points: 12,
    weakness: "Any ×2+ combo",
    reward: "Drops Heal Shard",
    ability: "Every 10s: plants 1 trap block — if matched, deals 8 dmg back to player",
  },
  StormfjordRaider: {
    key: "StormfjordRaider",
    name: "Stormfjord Raider",
    type: "Enemy — Human",
    description: "A fearless frost barbarian who charges up a catastrophic slam.",
    maxHP: 100,
    damageMin: 9,
    damageMax: 14,
    attackInterval: 20000,
    points: 26,
    weakness: "Any ×3+ combo",
    reward: "Drops Combo Surge",
    ability: "Every 20s: charges a slam — if not interrupted, deals 40 dmg flat",
  },
  StormfjordSoldier: {
    key: "StormfjordSoldier",
    name: "Stormfjord Soldier",
    type: "Enemy — Human",
    description: "A hardened frost-warrior immune to cold — and happy to reflect it.",
    maxHP: 80,
    damageMin: 7,
    damageMax: 11,
    attackInterval: 12000,
    points: 18,
    weakness: "Any ×3+ combo",
    reward: "Drops Ward powerup",
    ability: "Every 12s: freezes 1 full row for 6s (blocks unmatchable)",
  },
  StormfjordRefugee: {
    key: "StormfjordRefugee",
    name: "Stormfjord Refugee",
    type: "Enemy — Human",
    description: "A gaunt, hollow-eyed survivor — erratic, desperate, and surprisingly disruptive.",
    maxHP: 50,
    damageMin: 4,
    damageMax: 5,
    attackInterval: 8000,
    points: 9,
    weakness: "Any ×2+ combo instantly defeats it",
    reward: "30% chance to drop Heal Shard",
    ability: "Every 8s: corrupts 1 random block into a grey useless block",
  },
  Manfrog: {
    key: "Manfrog",
    name: "Manfrog",
    type: "Enemy — Beast",
    description: "A bloated amphibious horror that coats the board in toxic slime.",
    maxHP: 95,
    damageMin: 8,
    damageMax: 12,
    attackInterval: 14000,
    points: 24,
    weakness: "Any ×3+ combo defeats it",
    reward: "Clears all slime on board on defeat",
    ability: "Every 14s: slimes 1 full row — slimed blocks count as −1 combo value when matched",
  },
  GiantSpider: {
    key: "GiantSpider",
    name: "Giant Spider",
    type: "Enemy — Beast",
    description: "A massive arachnid weaving webs across the ruins — patient and methodical.",
    maxHP: 115,
    damageMin: 9,
    damageMax: 14,
    attackInterval: 15000,
    points: 20,
    weakness: "Any ×3+ combo defeats it",
    reward: "Drops Ward powerup; clears all webs on defeat",
    ability: "Every 15s: webs 2 random columns together — matching one pulls the other down",
  },
  Spider: {
    key: "Spider",
    name: "Spider",
    type: "Enemy — Beast",
    description: "A skittering little horror — fast, venomous, and irritating in groups.",
    maxHP: 40,
    damageMin: 4,
    damageMax: 5,
    attackInterval: 8000,
    points: 8,
    weakness: "Any ×2+ combo",
    reward: "10% chance to drop Heal Shard",
    ability: "Every 8s: injects venom into 1 block — matching it deals −2 HP to player",
  },
};

export const DEFAULT_ENEMY_KEY = "Goblin";
