// ─── Powerup definitions ─────────────────────────────────────────────────────
// Berisi data powerup / enhancement yang bisa muncul sebagai block spesial di grid.

export const POWERUP_TEMPLATES = {
  healShard: {
    id: "healShard",
    name: "Heal Shard",
    icon: "💚",
    rarity: "common",
    trigger: "onMatch",
    effect: "heal",
    amount: 15,
    duration: null,
    canStack: true,
    notes: "Auto on match. Restores player HP.",
  },
  ward: {
    id: "ward",
    name: "Ward",
    icon: "🛡️",
    rarity: "uncommon",
    trigger: "onEnemyAttack",
    effect: "shield",
    amount: 1,
    duration: null,
    canStack: false,
    notes: "Blocks next enemy hit. Cannot block Berserker Charge.",
  },
  comboSurge: {
    id: "comboSurge",
    name: "Combo Surge",
    icon: "⚡",
    rarity: "uncommon",
    trigger: "nextCombo",
    effect: "comboBoost",
    amount: 1,
    duration: 1,
    canStack: false,
    notes: "Next combo counts as one tier higher.",
  },
  ignite: {
    id: "ignite",
    name: "Ignite",
    icon: "🔥",
    rarity: "uncommon",
    trigger: "manual",
    effect: "clearColor",
    amount: null,
    duration: null,
    canStack: false,
    notes: "Tap to activate. Clears one block color from the board.",
  },
  freeze: {
    id: "freeze",
    name: "Freeze",
    icon: "❄️",
    rarity: "rare",
    trigger: "onPickup",
    effect: "pauseEnemy",
    amount: 8000,
    duration: 8000,
    canStack: true,
    notes: "Auto on pickup. Pauses enemy attacks.",
  },
  clarity: {
    id: "clarity",
    name: "Clarity",
    icon: "🔍",
    rarity: "rare",
    trigger: "onPickup",
    effect: "highlightPlacement",
    amount: null,
    duration: null,
    canStack: false,
    notes: "Auto on pickup. Highlights a strong placement until next move.",
  },
  bloodPact: {
    id: "bloodPact",
    name: "Blood Pact",
    icon: "🩸",
    rarity: "very rare",
    trigger: "manual",
    effect: "doubleDamage",
    amount: 2,
    duration: 1,
    canStack: false,
    notes: "Tap to activate. Next combo deals double damage but costs 5 HP.",
  },
  darkVeil: {
    id: "darkVeil",
    name: "Dark Veil",
    icon: "🕯️",
    rarity: "rare",
    trigger: "onPickup",
    effect: "cleanseCorruption",
    amount: null,
    duration: null,
    canStack: false,
    notes: "Auto on pickup. Clears corrupted blocks.",
  },
  soulBurst: {
    id: "soulBurst",
    name: "Soul Burst",
    icon: "💥",
    rarity: "very rare",
    trigger: "nextCombo",
    effect: "hitAllEnemies",
    amount: 1,
    duration: 1,
    canStack: false,
    notes: "Auto on next combo after pickup. Hits all active enemies.",
  },
  ironWill: {
    id: "ironWill",
    name: "Iron Will",
    icon: "🧭",
    rarity: "uncommon",
    trigger: "onLowHP",
    effect: "reduceDamage",
    amount: 10,
    duration: 10000,
    canStack: false,
    notes: "Auto when HP drops below 25%. Reduces incoming damage for 10s.",
  },
  plagueToken: {
    id: "plagueToken",
    name: "Plague Token",
    icon: "☠️",
    rarity: "negative",
    trigger: "onPickup",
    effect: "corruptBlocks",
    amount: 5,
    duration: 8000,
    canStack: true,
    notes: "Negative drop. Corrupts blocks and damages the player.",
  },
};

export const POWERUP_IDS = Object.keys(POWERUP_TEMPLATES);

export function randPowerupId() {
  return POWERUP_IDS[Math.floor(Math.random() * POWERUP_IDS.length)];
}

export const POWERUP_SPAWN_DELAY_MS = {
  min: 9000,
  max: 18000,
};
